export const environment = {
  production: true,
  userApiBaseUrl: "https://panalearn.com/dev/api",
  loginUrl: "/auth/login",
  signupUrl: "/auth/register",
  tokenValidationUrl: "/auth/token-validate",
  categoryUrl: "/categories",
  courseByCategoryIdUrl: "/categories/courses",
  courseSummary: "/courses",
  featureMediaUrl: "/media",
  courseSectionUrl:"/courses/<courseId>/chapter",
  courseQuizUrl:"/courses/<courseId>/quiz",
  courseQueUrl:"/courses/que",
  localCoursePrefix: "pana_course_",
  searchCoursesUrl: "/search?entity=courses",
  searchUsersUrl: "/search?entity=users",
};
