export const environment = {
  production: true,
  userApiBaseUrl: "https://panalearn.com/dev/api",
  loginUrl: "/auth/login",
  signupUrl: "/auth/register",
  profileUrl: "/users/profile",
  publicUserProfileUrl: "/public/users/profile",
  tokenValidationUrl: "/auth/token-validate",
  categoryUrl: "/categories",
  courseByCategoryIdUrl: "/categories/courses",
  courseSummary: "/courses",
  featureMediaUrl: "/media",
  courseSectionUrl: "/courses/<courseId>/chapter",
  courseQuizUrl: "/courses/<courseId>/quiz",
  courseQueUrl: "/courses/que",
  startQuizUrl: "/quiz/start",
  submitQuizUrl: "/quiz/submit-quiz",
  submitQuizAnsUrl: "/quiz/submit-answer",
  localCoursePrefix: "pana_course_",
  localQuizPrefix: "pana_quiz_",
  localQuizQuestionPrefix: "pana_quiz_questions_",
  searchCoursesUrl: "/search/?entity=courses",
  searchUsersWpUrl: "/search/?entity=users",
  searchUsersUrl: "/search/users",
  allGroupsInCourseUrl: "/tutor-groups/course",
  addGroupInCourseUrl: "/tutor-groups/create",
  addMemberInGroupUrl: "/tutor-groups/members"
};
